### ISSUE TITLE
Error importing IdP configuration from metadata https://idserver.servizicie.interno.gov.it/idp/shibboleth?Metadata

### ISSUE THREAD

**Issue by htsoft** [nicolabeghin/keycloak-cieid-provider-configuration-client#1]
Good morning,

I'm trying to install Keycloak 23.0.7 with the plugin of lscorcia, and using your script for the configuration.

when i start the command npm run create-idps, after a while i receive this error:

Error deleting IdP cieid-production
HTTP 404 Not Found
Error deleting IdP cieid-testing
HTTP 404 Not Found
Error importing IdP configuration from metadata https://idserver.servizicie.interno.gov.it/idp/shibboleth?Metadata
unknown_error
C:\Progetti\keycloack\keycloak-cieid-provider-configuration-client\node_modules\rxjs\internal\util\hostReportError.js:4
    setTimeout(function () { throw err; }, 0);
                             ^

TypeError: Cannot read properties of undefined (reading 'data')
    at C:\Progetti\keycloack\keycloak-cieid-provider-configuration-client\createidps.js:40:179
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.17.1

How can i solve the issue?

**Comment by htsoft** [comment]
This is the error on keycloak side:
2024-02-27 12:10:14,374 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-47) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.broker.provider.IdentityProviderFactory.parseConfig(org.keycloak.models.KeycloakSession, java.io.InputStream)" because "providerFactory" is null
2024-02-27 13:10:14     at org.keycloak.services.resources.admin.IdentityProvidersResource.importFrom(IdentityProvidersResource.java:161)
2024-02-27 13:10:14     at org.keycloak.services.resources.admin.IdentityProvidersResource$quarkusrestinvoker$importFrom_d5d7eb29b13c7a2b1190af4938352b6a37293cc9.invoke(Unknown Source)
2024-02-27 13:10:14     at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
2024-02-27 13:10:14     at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
2024-02-27 13:10:14     at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
2024-02-27 13:10:14     at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
2024-02-27 13:10:14     at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
2024-02-27 13:10:14     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
2024-02-27 13:10:14     at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2024-02-27 13:10:14     at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2024-02-27 13:10:14     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-02-27 13:10:14     at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by nicolabeghin** [comment]
Ciao, fixato in https://github.com/nicolabeghin/keycloak-cieid-provider-configuration-client/commit/1b58847e55025da150a3f33fcd495fdc4accf599 - il client faceva riferimento al provider SPID che non essendo installato nella tua istanza faceva fallire l'import del metadata

**Comment by htsoft** [comment]
Ciao,
innanzitutto grazie per la risposta.

Lo script ora non da più quell'errore, ma restituisce questo:
Error deleting IdP cieid-testing
HTTP 404 Not Found
Error deleting IdP cieid-production
HTTP 404 Not Found
Error creating IdP cieid-testing
unknown_error
Error creating IdP cieid-production
unknown_error
HTTP 404 Not Found
HTTP 404 Not Found
HTTP 404 Not Found
HTTP 404 Not Found
HTTP 404 Not Found
HTTP 404 Not Found
HTTP 404 Not Found
HTTP 404 Not Found
HTTP 404 Not Found
HTTP 404 Not Found

E nel log vi è questo:
{
  alias: 'cieid-testing',
  create_response: undefined,
  mapper_response: [ undefined, undefined, undefined, undefined, undefined ]
}
{
  alias: 'cieid-production',
  create_response: undefined,
  mapper_response: [ undefined, undefined, undefined, undefined, undefined ]
}

Il realm cied l'ho creato io (e per sicurezza ho creato anche il realm spid)

questo è il mio file .env:
```
# target Keycloak URL
keycloakServerBaseURL = http://localhost:8080
adminRealm = master
adminUsername = admin
adminPwd = change_me
adminClientId = admin-cli
realm = cied

# CIED Testing
createCiedTestingIdP = true
ciedTestingIdPAlias = Testing
cieidTestingIdPMetadataURL = https://preproduzione.idserver.servizicie.interno.gov.it/idp/shibboleth?Metadata

# CIED Production
cieidIdPMetadataURL = https://idserver.servizicie.interno.gov.it/idp/shibboleth?Metadata

# additional metadata info
organizationDisplayNames = en|Organization name,it|Organization name

# Please note:
# Authentication Flow "First Broker Login (SPID)" must be created: 
# https://github.com/italia/spid-keycloak-provider/wiki/Configuring-the-Authentication-Flow
# official organizationNames can be retrieved from https://indicepa.gov.it/ipa-portale/consultazione/indirizzo-sede/ricerca-ente
# official organizationMunicipality can be retrieved from https://www1.agenziaentrate.gov.it/servizi/codici/ricerca/VisualizzaTabella.php?ArcName=COM-ICI

organizationNames = en|Organization name from IndicePA,it|Organization name from IndicePA
otherContactPhone = +3912345678
otherContactEmail = test@pec.it
otherContactIpaCode = xxxxxx
organizationUrls = en|https://organization.com,it|https://organization.com
organizationMunicipality = ISTAT_Code
```

**Comment by nicolabeghin** [comment]
Hai creato il "First Broker Login (SPID)"?

**Comment by htsoft** [comment]
No, ora lo creo grazie mille

**Comment by freddy34** [comment]
```
Error retrieving Keycloak token
Unable to find matching target resource method
Error retrieving Keycloak token
Unable to find matching target resource method
Error deleting IdP cieid-testing
Unable to find matching target resource method
Error deleting IdP cieid-production
Unable to find matching target resource method
Error retrieving Keycloak token
Unable to find matching target resource method
Error importing IdP configuration from metadata https://preproduzione.idserver.servizicie.interno.gov.it/idp/shibboleth?Metadata
Unable to find matching target resource method
...omissis.../keycloak-cieid-provider-configuration-client/node_modules/rxjs/internal/util/hostReportError.js:4
    setTimeout(function () { throw err; }, 0);
                             ^

TypeError: Cannot read properties of undefined (reading 'data')
    at ...omissis.../keycloak-cieid-provider-configuration-client/createidps.js:52:90
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.18.3
```
- Keycloak: __26.1.3__
- SPID provider: __installato__
- First Broker Login (SPID): __presente__
- log Keycloak: nessun errore

**Comment by nicolabeghin** [comment]
> Unable to find matching target resource method

wrong Keycloak endpoint probably missing or requiring `/auth` in path

**Comment by freddy34** [comment]
> > Unable to find matching target resource method
> 
> wrong Keycloak endpoint probably missing or requiring `/auth` in path

simply remove hard-coded /auth/ from url concatenation in https.js cause that scenario is valid for legacy Keycloak but not for Quarkus one (at least for me)

**Comment by namadori** [comment]
I had the same issue, solved by removing `/auth` from the path in `http.js` lines 21, 50, 73, 94, 113, 131, 158.
